/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WeatherWagerBook } from "./WeatherWagerBook";
export type { WeatherWagerBookFixed } from "./WeatherWagerBookFixed";
export type { WeatherWagerMock } from "./WeatherWagerMock";
